// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3P3HHOsrNrk9x4vRzj0a3isM9gwS8jJ8',
    appId: '1:610399892075:web:52042e4ed36f4d2989772e',
    messagingSenderId: '610399892075',
    projectId: 'party-bee-30d70',
    authDomain: 'party-bee-30d70.firebaseapp.com',
    storageBucket: 'party-bee-30d70.firebasestorage.app',
    measurementId: 'G-2T9G3W125N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHTyHMqBASIMKkGKnBjF1iUAk9bb3Gs_g',
    appId: '1:610399892075:android:b5500588bbbedb3a89772e',
    messagingSenderId: '610399892075',
    projectId: 'party-bee-30d70',
    storageBucket: 'party-bee-30d70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHTyHMqBASIMKkGKnBjF1iUAk9bb3Gs_g',
    appId: '1:610399892075:ios:b5500588bbbedb3a89772e',
    messagingSenderId: '610399892075',
    projectId: 'party-bee-30d70',
    storageBucket: 'party-bee-30d70.firebasestorage.app',
    iosBundleId: 'com.example.partybee',
  );
}
